export enum ActionTypes {
  // BULK UPDATE
  UPDATE_SELECTED_QUERY = 'UPDATE_SELECTED_QUERY',
  ADD_SINGLE_SELECTED_QUERY = 'ADD_SINGLE_SELECTED_QUERY',
  REMOVE_SINGLE_SELECTED_QUERY = 'REMOVE_SINGLE_SELECTED_QUERY'
}
