export enum MutationTypes {
  ADD_SELECTED_QUERY = 'ADD_SELECTED_QUERY',
  REMOVE_SELECTED_QUERY = 'REMOVE_SELECTED_QUERY',
  ADD_MULTIPLE_SELECTED_QUERIES = 'ADD_MULTIPLE_SELECTED_QUERIES',
  RESET_SELECTED_QUERIES = 'RESET_SELECTED_QUERIES',
  SET_ALL_QUERIES = 'SET_ALL_QUERIES'
}
