version: "3"
services:
  api-gateway-service:
    build: "./api-gateway"
    restart: "always"
    depends_on:
      - users-service-db
      - listings-service
      - books-service
    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.29
    ports:
      - 0.0.0.0:7201:3306
    volumes:
      - /var/lib/mysql

  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
      - events-service
    environment:
      - DB_URI=mysql://root:password@listings-service-db/db?charset=UTF8
    ports:
      - 7100:7100
    volumes:
      - ./listings-service:/opt/app

  listings-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - /var/lib/mysql
    image: mysql:5.7.29
    ports:
      - 0.0.0.0:7200:3306

  books-service:
    build: "./books-service"
    depends_on:
      - books-service-db
      - events-service
    environment:
      - DB_URI=mysql://root:password@books-service-db/db?charset=UTF8
    ports:
      - 7102:7102
    volumes:
      - ./books-service:/opt/app

  books-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - /var/lib/mysql
    image: mysql:5.7.29
    ports:
      - 0.0.0.0:7202:3306

  events-service:
    image: rabbitmq:3-management
    environment: 
      - RABBITMQ_ERLANG_COOKIE='secretcookie'
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 25672:25672