export enum MutationTypes {
  ADD_SELECTED_CATEGORY = 'ADD_SELECTED_CATEGORY',
  REMOVE_SELECTED_CATEGORY = 'REMOVE_SELECTED_CATEGORY',
  ADD_MULTIPLE_SELECTED_CATEGORIES = 'ADD_MULTIPLE_SELECTED_CATEGORIES',
  RESET_SELECTED_CATEGORIES = 'RESET_SELECTED_CATEGORIES',
  SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES'
}
