export enum MutationTypes {
  GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES',
  GET_SELECTED_CATEGORIES = 'GET_SELECTED_CATEGORIES',
  ADD_SELECTED_CATEGORY = 'ADD_SELECTED_CATEGORY',
  REMOVE_SELECTED_CATEGORY = 'REMOVE_SELECTED_CATEGORY',
}
